### ISSUE TITLE
[bug] Agent Mode: opencode acp stdin/stdout mode crashes on Windows with "ServeError" — blocks OpenCode backend entirely

### ISSUE THREAD

**Issue by cgartlab** [logancyang/obsidian-copilot#2933]
## Summary

On Windows 11, enabling Agent Mode with **OpenCode** as the backend consistently fails with `"ACP connection closed"`. The root cause is that `opencode acp` in **stdin/stdout pipe mode** (the only mode your plugin spawns with) crashes after `init` with exit code 1 and `ServeError`. This affects **all** OpenCode versions tested (1.18.16, 1.18.18, 1.18.19).

The TCP mode (`--port 0` / `--port <N>`) works, but: (a) stdout never outputs the assigned port, and (b) the plugin has no mechanism to discover a TCP port — it only supports stdin/stdout pipes.

**This is a hard blocker for OpenCode as an Agent Mode backend on Windows.** No user-side workaround exists.

---

## Environment

- **OS**: Windows 11 Home, build 26200
- **Node.js**: v26.2.0
- **OpenCode**: `opencode-ai@1.18.19` (npm)
- **Binary**: `C:\Users\cgart\AppData\Roaming\npm\node_modules\opencode-ai\bin\opencode.exe`
- **Copilot plugin**: v4.0.0
- **Vault**: `D:\github-repos\cgartlab-obsidian` (Obsidian desktop)

---

## Symptom

After configuring Agent Mode with OpenCode and toggling it on, Obsidian shows:
ACP connection closed [AgentMode] initialize failed for opencode; tearing down subprocess Error: ACP connection closed

The plugin's AcpProcessManager spawns the binary with `stdio: ["pipe","pipe","pipe"]` and args `["acp", "--cwd", vaultPath]`. The process exits after ~300ms with code 1.

---

### Step 1: Config Migration Issue (FIXED)

After upgrading Copilot plugin from v3.2.8 → v4.0.0, `agentMode.backends.opencode` in `data.json` was reset to `{}`. The binary path was still in the old `deviceProfiles` section. v4.0.0 reads from `backends.opencode` only.

**Fix applied**: Re-added `binaryPath`, `binaryVersion`, `binarySource` to `agentMode.backends.opencode` in `data.json`.

### Step 2: Invalid Plugin Entries in opencode Config (FIXED)

Two config files had invalid `plugin` entries causing opencode to crash:

| Config file | Bad entry | Error |
|---|---|---|
| `~/.config/opencode/opencode.json` | `"plugin": ["oh-my-opencode-slim@latest"]` | `Plugin export is not a function` |
| `~/.opencode/opencode.json` | `"plugin": ["list"]` | `Plugin export is not a function` |

**Fix applied**: Removed both `plugin` arrays, cleaned `node_modules` and `.oh-my-opencode-slim` directories.

### Step 3: The Remaining Bug — ACP stdin/stdout Mode Crash

After fixing steps 1 and 2, the problem persists. The issue is in **opencode itself**, not the plugin config.

---

### FAILING: stdin/stdout pipe mode (default, what your plugin uses)
opencode acp --cwd

Output (stderr):
level=INFO message="creating instance" level=INFO message="bootstrapping" level=INFO message="all LSPs are disabled" level=INFO message="all formatters are disabled" level=INFO message=init level=INFO message="setup connection" level=INFO message="disposing instance" Error: Unexpected error

ServeError

**Exit code: 1** | **Duration: ~300ms** | **Reproducible: 100%**

### WORKING: TCP mode (`--port 0`)
opencode acp --cwd --port 0

Output (stderr):
level=INFO message=init level=INFO message="setup connection" level=INFO message="global event connected"

Process stays alive. **But stdout is empty** — port number never reported, so a parent cannot discover it.

### WORKING: Other opencode commands
opencode run "hello" # ✅ exit 0 opencode debug info # ✅ exit 0 opencode --version # ✅ 1.18.19

### Version Testing

| Version | stdin/stdout | TCP (`--port 0`) |
|---------|-------------|-------------------|
| 1.18.16 | ❌ Exit 1  | ✅ Works          |
| 1.18.18 | ❌ Exit 1  | ✅ Works          |
| 1.18.19 | ❌ Exit 1  | ✅ Works          |

The bug exists across all recent versions. The upstream Go binary `opencode-ai/opencode` has been archived and the project moved to `charmbracelet/crush` (restricts issue creation).

---

## Why This Blocks Your Plugin

Your AcpProcessManager spawns with:
```js
spawn(binaryPath, ["acp", "--cwd", vaultBasePath], {
  stdio: ["pipe", "pipe", "pipe"]
});

**Comment by zeroliu** [comment]
Next step: reproduce on the current supported OpenCode build on Windows, then make a maintainer choice: add a supported TCP transport with deterministic port discovery, or document the upstream blocker and pin a known-working build. The report is detailed enough; the remaining blocker is that product/transport decision.

**Comment by zeroliu** [comment]
Tested in VMware Fusion on Windows 11 ARM with Copilot 4.0.7 and OpenCode 1.18.16, using Obsidian's embedded Node 24.18.1:

- Three fresh OpenCode processes completed ACP initialization and session creation using Copilot's stdin/stdout pipe settings. No `ServeError` or early exit.
- In the Copilot UI, OpenCode Zen/Big Pickle returned the requested `WINDOWS_OPENCODE_2933_OK` response in six seconds, exercising the real launch and generated configuration.

We couldn't reproduce the failure, so no transport change or fix was made. This differs from the reported Copilot 4.0.0 environment and does not rule out an environment-specific issue. Closing for now; please reopen with updated versions and startup stderr if it still occurs on the current release.
